site_name: PG-Strom Manual
site_description: PG-Strom v2.0 Official Documentation
site_author: PG-Strom Development Team
theme:
    name: readthedocs
@en{
    custom_dir: docs/custom_en
}
@ja{
    custom_dir: docs/custom_ja
}
nav:
@en{
- 'Home' : 'index.md'
- 'Install' : 'install.md'
- 'Tutorial' :
    - 'Basic Operations' : 'operations.md'
    - 'BRIN Index' : 'brin.md'
    - 'Partitioning' : 'partition.md'
    - 'PostGIS' : 'postgis.md'
    - 'Trouble Shooting' : 'troubles.md'
- 'Advanced Features' :
    - 'GPUDirect SQL' : 'ssd2gpu.md'
    - 'Apache Arrow' : 'arrow_fdw.md'
    - 'GPU Cache' : 'gpucache.md'
- 'References' :
    - 'Data Types' : 'ref_types.md'
    - 'Functions and Operators' : 'ref_devfuncs.md'
    - 'SQL Objects' : 'ref_sqlfuncs.md'
    - 'GUC Parameters' : 'ref_params.md'
- 'Release Note' :
    - 'PG-Strom v3.0' : 'release_v3.0.md'
    - 'PG-Strom v2.3' : 'release_v2.3.md'
    - 'PG-Strom v2.2' : 'release_v2.2.md'
    - 'PG-Strom v2.0' : 'release_v2.0.md'
}
@ja{
- 'はじめに' : 'index.md'
- 'インストール' : 'install.md'
- '利用ガイド' :
    - '基本的な操作' : 'operations.md'
    - 'BRINインデックス' : 'brin.md'
    - 'パーティション' : 'partition.md'
    - 'GPU版PostGIS' : 'postgis.md'
    - 'トラブルシューティング' : 'troubles.md'
- '先進機能' :
    - 'GPUダイレクトSQL' : 'ssd2gpu.md'
    - 'Apache Arrow' : 'arrow_fdw.md'
    - 'GPUキャッシュ' : 'gpucache.md'
- 'リファレンス' :
    - 'データ型' : 'ref_types.md'
    - '関数と演算子' : 'ref_devfuncs.md'
    - 'SQLオブジェクト' : 'ref_sqlfuncs.md'
    - 'GUCパラメータ' : 'ref_params.md'
- 'リリースノート' :
    - 'PG-Strom v3.0' : 'release_v3.0.md'
    - 'PG-Strom v2.3' : 'release_v2.3.md'
    - 'PG-Strom v2.2' : 'release_v2.2.md'
    - 'PG-Strom v2.0' : 'release_v2.0.md'
}
extra_css:
    - "//fonts.googleapis.com/earlyaccess/notosansjp.css"
    - "//fonts.googleapis.com/css?family=Open+Sans:600,800"
    - "custom.css"
markdown_extensions:
    - admonition
    - footnotes
    - def_list
